from __future__ import annotations

from pathlib import Path


PRESET_PROFILE_DIR = Path(__file__).resolve().parents[1] / "profiles" / "presets"
CUSTOM_PROFILE_DIR = Path(__file__).resolve().parents[1] / "profiles" / "custom"
DEFAULT_PROFILE_ID = "coated_fogra39l_vigc_300"


def profile(
    profile_id: str,
    group: str,
    name: str,
    filename: str,
    description: str,
    standard: str,
    region: str,
    paper_type: str,
    tac: str,
    paper_class: str,
    display: str | None = None,
) -> dict[str, str]:
    return {
        "id": profile_id,
        "group": group,
        "name": name,
        "display": display or name,
        "description": description,
        "standard": standard,
        "region": region,
        "paper_type": paper_type,
        "tac": tac,
        "paper_class": paper_class,
        "filename": filename,
    }


PRESET_PROFILES = [
    profile(
        "aptec_cmykogv_coated_linearctv_2025",
        "International",
        "APTEC CMYKOGV Coated Linear CTV 2025",
        "APTEC_CMYKOGV_Coated_LinearCTV_2025.icc",
        "For coated APTEC CMYKOGV printing workflows using a linear CTV tone curve.",
        "APTEC 2025",
        "International",
        "Coated",
        "Printer dependent",
        "CMYKOGV coated stock",
        "APTEC CMYKOGV Coated Linear CTV 2025 | APTEC CMYKOGV \u6d82\u5c42\u7ebf\u6027 CTV 2025",
    ),
    profile(
        "aptec_flexo_coated_linearctv_2025",
        "International",
        "APTEC Flexo Coated Linear CTV 2025",
        "APTEC_Flexo_Coated_LinearCTV_2025.icc",
        "For coated flexographic printing workflows using a linear CTV tone curve.",
        "APTEC Flexo CTV 2025",
        "International",
        "Coated",
        "Printer dependent",
        "Flexo coated stock",
        "APTEC Flexo Coated Linear CTV 2025 | APTEC Flexo \u6d82\u5c42\u7ebf\u6027 CTV 2025",
    ),
    profile(
        "aptec_flexo_label_linearctv_2025",
        "International",
        "APTEC Flexo Label Linear CTV 2025",
        "APTEC_Flexo_Label_LinearCTV_2025.icc",
        "For flexographic label printing workflows using a linear CTV tone curve.",
        "APTEC Flexo CTV 2025",
        "International",
        "Label stock",
        "Printer dependent",
        "Label substrate",
        "APTEC Flexo Label Linear CTV 2025 | APTEC Flexo Label \u7ebf\u6027 CTV 2025",
    ),
    profile(
        "aptec_flexo_pvc_linearctv_2025",
        "International",
        "APTEC Flexo PVC Linear CTV 2025",
        "APTEC_Flexo_PVC_LinearCTV_2025.icc",
        "For flexographic PVC printing workflows using a linear CTV tone curve.",
        "APTEC Flexo CTV 2025",
        "International",
        "PVC",
        "Printer dependent",
        "PVC substrate",
        "APTEC Flexo PVC Linear CTV 2025 | APTEC Flexo PVC \u7ebf\u6027 CTV 2025",
    ),
    profile(
        "aptec_offset_coated_linearctv_2025",
        "International",
        "APTEC Offset Coated Linear CTV 2025",
        "APTEC_Offset_Coated_LinearCTV_2025.icc",
        "For coated offset printing workflows using a linear CTV tone curve.",
        "APTEC Offset CTV 2025",
        "International",
        "Coated",
        "Printer dependent",
        "Offset coated stock",
    ),
    profile(
        "aptec_offset_uncoated_linearctv_2025",
        "International",
        "APTEC Offset Uncoated Linear CTV 2025",
        "APTEC_Offset_Uncoated_LinearCTV_2025.icc",
        "For uncoated offset printing workflows using a linear CTV tone curve.",
        "APTEC Offset CTV 2025",
        "International",
        "Uncoated",
        "Printer dependent",
        "Offset uncoated stock",
    ),
    profile(
        "aptec_pc10_cardboard_2023_v1",
        "International",
        "APTEC PC10 CardBoard 2023 v1",
        "APTEC_PC10_CardBoard_2023_v1.icc",
        "For APTEC PC10 coated cardboard packaging stock.",
        "APTEC PC10 2023 v1",
        "International",
        "Cardboard",
        "Printer dependent",
        "Coated cardboard",
    ),
    profile(
        "aptec_pc11_ccnb_2023_v1",
        "International",
        "APTEC PC11 CCNB 2023 v1",
        "APTEC_PC11_CCNB_2023_v1.icc",
        "For APTEC PC11 CCNB packaging board stock.",
        "APTEC PC11 2023 v1",
        "International",
        "CCNB board",
        "Printer dependent",
        "Packaging board",
    ),
    profile(
        "coated_fogra39l_vigc_300",
        "Europe",
        "Coated Fogra39L_300%",
        "Coated_Fogra39L_VIGC_300.icc",
        "For improved white coated paper according to FOGRA39 characterization data with 300% TAC.",
        "ISO 12647-2:2004 | FOGRA39",
        "Europe",
        "Coated",
        "300%",
        "Paper #1, #2",
        "Coated Fogra39L_300% | \u6d82\u5c42 Fogra39L_300%",
    ),
    profile(
        "coated_fogra39l_vigc_260",
        "Europe",
        "Coated Fogra39L_260%",
        "Coated_Fogra39L_VIGC_260.icc",
        "For improved white coated paper according to FOGRA39 characterization data with 260% TAC.",
        "ISO 12647-2:2004 | FOGRA39",
        "Europe",
        "Coated",
        "260%",
        "Paper #1, #2",
    ),
    profile(
        "uncoated_fogra47l_vigc_300",
        "Europe",
        "Uncoated Fogra47L_300%",
        "Uncoated_Fogra47L_VIGC_300.icc",
        "For improved white uncoated paper according to FOGRA47 characterization data with 300% TAC.",
        "ISO 12647-2:2004 | FOGRA47",
        "Europe",
        "Uncoated",
        "300%",
        "Paper #4",
        "Uncoated Fogra47L_300% | \u672a\u6d82\u5c42 Fogra47L_300%",
    ),
    profile(
        "uncoated_fogra47l_vigc_260",
        "Europe",
        "Uncoated Fogra47L_260%",
        "Uncoated_Fogra47L_VIGC_260.icc",
        "For improved white uncoated paper according to FOGRA47 characterization data with 260% TAC.",
        "ISO 12647-2:2004 | FOGRA47",
        "Europe",
        "Uncoated",
        "260%",
        "Paper #4",
    ),
    profile(
        "pso_coated_v3",
        "Europe",
        "PSO Coated v3",
        "PSOcoated_v3.icc",
        "Modern European profile for premium coated paper based on FOGRA51.",
        "ISO 12647-2:2013 | FOGRA51",
        "Europe",
        "Coated",
        "300%",
        "Paper #1, #2",
        "PSO Coated v3 | PSO \u6d82\u5c42 v3",
    ),
    profile(
        "pso_uncoated_v3_fogra52",
        "Europe",
        "PSO Uncoated v3 FOGRA52",
        "PSOuncoated_v3_FOGRA52.icc",
        "Modern European profile for wood-free uncoated paper based on FOGRA52.",
        "ISO 12647-2:2013 | FOGRA52",
        "Europe",
        "Uncoated",
        "300%",
        "Paper #5",
        "PSO Uncoated v3 | PSO \u65e0\u6d82\u5c42 v3",
    ),
    profile(
        "psosc_b_paper_v3_fogra54",
        "Europe",
        "PSO SC-B Paper v3 FOGRA54",
        "PSOsc-b_paper_v3_FOGRA54.icc",
        "European profile for supercalendered SC-B paper based on FOGRA54.",
        "ISO 12647-2:2013 | FOGRA54",
        "Europe",
        "SC-B Paper",
        "270%",
        "Supercalendered paper",
    ),
    profile(
        "sc_paper_eci",
        "Europe",
        "SC Paper ECI",
        "SC_paper_eci.icc",
        "European profile for supercalendered paper.",
        "ECI / ISO 12647-2",
        "Europe",
        "SC Paper",
        "270%",
        "Supercalendered paper",
    ),
    profile(
        "gracol2013_crpc6",
        "North America",
        "GRACoL2013 CRPC6",
        "GRACoL2013_CRPC6.icc",
        "North American profile for premium coated sheetfed offset printing.",
        "CGATS21-2 | CRPC6",
        "North America",
        "Coated",
        "320%",
        "Premium coated",
    ),
    profile(
        "gracol2013unc_crpc3",
        "North America",
        "GRACoL2013UNC CRPC3",
        "GRACoL2013UNC_CRPC3.icc",
        "North American profile for uncoated printing conditions.",
        "CGATS21-2 | CRPC3",
        "North America",
        "Uncoated",
        "300%",
        "Uncoated stock",
    ),
    profile(
        "gracol2006_coated1v2",
        "North America",
        "GRACoL2006 Coated1 v2",
        "GRACoL2006_Coated1v2.icc",
        "Legacy North American profile for GRACoL 2006 coated printing.",
        "GRACoL 2006",
        "North America",
        "Coated",
        "350%",
        "Coated #1",
    ),
    profile(
        "swop2013c3_crpc5",
        "North America",
        "SWOP2013 C3 CRPC5",
        "SWOP2013C3_CRPC5.icc",
        "North American profile for publication-grade web offset printing.",
        "CGATS21-2 | CRPC5",
        "North America",
        "Publication coated",
        "300%",
        "Publication stock",
    ),
    profile(
        "swop2006_coated3v2",
        "North America",
        "SWOP2006 Coated3 v2",
        "SWOP2006_Coated3v2.icc",
        "Legacy North American profile for SWOP 2006 coated #3 publication stock.",
        "SWOP 2006",
        "North America",
        "Publication coated #3",
        "300%",
        "Coated #3",
    ),
    profile(
        "swop2006_coated5v2",
        "North America",
        "SWOP2006 Coated5 v2",
        "SWOP2006_Coated5v2.icc",
        "Legacy North American profile for SWOP 2006 coated #5 publication stock.",
        "SWOP 2006",
        "North America",
        "Publication coated #5",
        "300%",
        "Coated #5",
    ),
    profile(
        "snap2007",
        "North America",
        "SNAP2007",
        "SNAP2007.icc",
        "North American profile for newspaper advertising production.",
        "SNAP 2007",
        "North America",
        "Newsprint",
        "220%",
        "Newspaper stock",
    ),
    profile("cgats21_crpc1", "North America", "CGATS21 CRPC1", "CGATS21_CRPC1.icc", "CGATS21 reference printing condition CRPC1.", "CGATS21-2 | CRPC1", "North America", "Reference print condition", "Condition dependent", "CRPC1"),
    profile("cgats21_crpc2", "North America", "CGATS21 CRPC2", "CGATS21_CRPC2.icc", "CGATS21 reference printing condition CRPC2.", "CGATS21-2 | CRPC2", "North America", "Reference print condition", "Condition dependent", "CRPC2"),
    profile("cgats21_crpc3", "North America", "CGATS21 CRPC3", "CGATS21_CRPC3.icc", "CGATS21 reference printing condition CRPC3.", "CGATS21-2 | CRPC3", "North America", "Reference print condition", "Condition dependent", "CRPC3"),
    profile("cgats21_crpc4", "North America", "CGATS21 CRPC4", "CGATS21_CRPC4.icc", "CGATS21 reference printing condition CRPC4.", "CGATS21-2 | CRPC4", "North America", "Reference print condition", "Condition dependent", "CRPC4"),
    profile("cgats21_crpc5", "North America", "CGATS21 CRPC5", "CGATS21_CRPC5.icc", "CGATS21 reference printing condition CRPC5.", "CGATS21-2 | CRPC5", "North America", "Reference print condition", "Condition dependent", "CRPC5"),
    profile("cgats21_crpc6", "North America", "CGATS21 CRPC6", "CGATS21_CRPC6.icc", "CGATS21 reference printing condition CRPC6.", "CGATS21-2 | CRPC6", "North America", "Reference print condition", "Condition dependent", "CRPC6"),
    profile("cgats21_crpc7", "North America", "CGATS21 CRPC7", "CGATS21_CRPC7.icc", "CGATS21 reference printing condition CRPC7.", "CGATS21-2 | CRPC7", "North America", "Reference print condition", "Condition dependent", "CRPC7"),
    profile(
        "japan_color_2011_coated",
        "Japan",
        "Japan Color 2011 Coated",
        "JapanColor2011Coated.icc",
        "Japanese profile for coated paper offset printing.",
        "Japan Color 2011",
        "Japan",
        "Coated",
        "350%",
        "Coated stock",
        "Japan Color 2011 Coated | \u65e5\u672c\u8272\u5f69 2011 \u6d82\u5c42",
    ),
]


def ensure_profile_dirs() -> None:
    PRESET_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
    CUSTOM_PROFILE_DIR.mkdir(parents=True, exist_ok=True)


def preset_by_id(profile_id: str) -> dict[str, str] | None:
    for preset in PRESET_PROFILES:
        if preset["id"] == profile_id:
            return preset
    return None


def resolve_preset_path(profile_id: str) -> Path | None:
    preset = preset_by_id(profile_id)
    if not preset:
        return None

    candidates = [
        PRESET_PROFILE_DIR / preset["filename"],
        PRESET_PROFILE_DIR / f"{profile_id}.icc",
        PRESET_PROFILE_DIR / f"{profile_id}.icm",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None
